module.exports = {
  GREEN_TICK: '<a:Green_tick_mark:1479393702031134730>',
  RED_CROSS: '<a:Red_cross_mark:1479397724603416606>',
  BAR_CHART: '<a:Bar_chart:1479397726679470111>',
  LOCK: '🔒',
  UNLOCK: '🔓',
  TICKET: '🎫',
  CLOSE: '❌',
  DELETE: '🗑️',
  CLAIM: '🙋',
  UNCLAIM: '🙅',
  ADD: '➕',
  REMOVE: '➖',
  TRANSCRIPT: '📄',
  RENAME: '✏️',
  WARN: '⚠️',
  INFO: 'ℹ️',
  SUCCESS: '✅',
  ERROR: '❌',
  LOADING: '⏳',
  // Music related (add if missing)
  MUSIC: '🎵',
  PLAYLIST: '📀',
  SKIP: '⏭️',
  STOP: '🛑',
  QUEUE: '📋',
  PLAY: '▶️',
  PAUSE: '⏸️',
  RESUME: '▶️',
  VOLUME: '🔊',
  REPEAT: '🔁',
  SHUFFLE: '🔀'
};